export const userColumns = [
  {
    title: 'Organization Name',
    dataIndex: 'name',
    key: 'name',

    sorter: (a: any, b: any) => {
      console.log(a.name);
      return a.name.length - b.name.length;
    },
    sortDirections: ['descend'],
  },
  {
    title: 'Email Address',
    dataIndex: 'email',
    key: 'email',
  },
  {
    title: 'Phone number',
    dataIndex: 'phone',
    key: 'phone',
  },
  {
    title: 'Created on',
    dataIndex: 'created',
    key: 'created',
  },
  {
    title: 'Action',
    dataIndex: 'action',
    key: 'action',
  },
];
export const userDataSource = [
  {
    name: 'Company 1',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 2',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 3',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 4',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 5',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 6',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 7',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 8',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 9',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 10',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 11',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 12',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 13',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 14',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 15',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 16',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 17',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 18',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 19',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 20',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 21',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 22',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 23',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
  {
    name: 'Company 24',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    action: 'some action',
  },
];

export const userDrawerBody = {
  userFields: [
    {
      title: 'First Name',
      id: 'fistName',
      type: 'text',
      name: 'fistName',
      defaultValue: '',
      errorMessage: 'Please enter the first name',
      placeholder: 'Enter your first name',
    },
    {
      title: 'Last Name',
      id: 'lastName',
      type: 'text',
      name: 'lastName',
      defaultValue: '',
      errorMessage: 'Please enter the last name',
      placeholder: 'Enter your last name',
    },
    {
      title: 'Email Address',
      id: 'email',
      type: 'text',
      name: 'email',
      defaultValue: '',
      errorMessage: 'Please enter the email address',
      placeholder: 'Enter your email address',
    },
    {
      title: 'Phone Number',
      id: 'phoneNumber',
      type: 'text',
      name: 'phoneNumber',
      defaultValue: '',
      errorMessage: 'Please enter the phone number',
      placeholder: 'Enter your phone number',
    },
  ],
};
