import {
  MailOutlined,
  LockOutlined,
  UserOutlined,
  PhoneOutlined,
} from '@ant-design/icons';

export const userColumns = [
  {
    title: 'Organization Name',
    dataIndex: 'name',
    key: 'name',
  },
  {
    title: 'Email Address',
    dataIndex: 'email',
    key: 'email',
  },
  {
    title: 'Phone number',
    dataIndex: 'phone',
    key: 'phone',
  },
  {
    title: 'Created on',
    dataIndex: 'created',
    key: 'created',
  },
  {
    title: 'Status',
    dataIndex: 'status',
    key: 'status',
  },
  {
    title: 'Action',
    dataIndex: 'action',
    key: 'action',
  },
];

export const userDataSource = [
  {
    name: 'Company 1',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 2',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 3',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 4',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 5',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 6',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 7',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 8',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 9',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 10',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 11',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 12',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 13',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 14',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 15',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 16',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 17',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 18',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 19',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 20',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 21',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 22',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 23',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
  {
    name: 'Company 24',
    email: 'hello @ gmail.com',
    phone: 7874445547,
    created: 'some date',
    status: true,
    action: 'some action',
  },
];

export const registerFormData = [
  {
    title: 'First Name',
    id: 'first_name',
    type: 'text',
    name: 'first_name',
    defaultValue: '',
    errorMessage: 'Please enter your first name',
    placeholder: 'Enter your first name',
    required: true,
    // icon: 'UserOutlined',
    icon: <UserOutlined className="register-icon" />,
    rules: [
      {
        required: true,
        message: 'Please input your first name!',
      },
    ],
  },
  {
    title: 'Last Name',
    id: 'last_name',
    type: 'text',
    name: 'last_name',
    defaultValue: '',
    errorMessage: 'Please enter your last name',
    placeholder: 'Enter your Last Name',
    required: true,
    // icon: 'UserOutlined',
    icon: <UserOutlined className="register-icon" />,
    rules: [
      {
        required: true,
        message: 'Please input your last name!',
      },
    ],
  },
  {
    title: 'Email Address',
    id: 'email',
    type: 'text',
    name: 'email',
    defaultValue: '',
    errorMessage: 'Please enter your email',
    placeholder: 'Enter your email address',
    required: true,
    // icon: 'MailOutlined',
    icon: <MailOutlined className="register-icon" />,
    rules: [
      {
        required: true,
        message: 'Please input your email address!',
      },
    ],
  },
  {
    title: 'Phone Number',
    id: 'phone',
    type: 'text',
    name: 'phone',
    defaultValue: '',
    errorMessage: 'Please input your phone number!',
    placeholder: 'Enter your Phone Number',
    required: true,
    // icon: 'PhoneOutlined',
    icon: <PhoneOutlined className="register-icon" />,
    rules: [
      {
        required: true,
        message: 'Please input your phone number!',
      },
    ],
  },
  {
    title: 'Password',
    id: 'password',
    type: 'password',
    name: 'password',
    defaultValue: '',
    errorMessage: 'Please input your password!',
    placeholder: 'Enter your Password',
    required: true,
    // icon: 'LockOutlined',
    icon: <LockOutlined className="register-icon" />,
    rules: [
      {
        required: true,
        message: 'Please input your password!',
      },
    ],
  },
  {
    title: 'Re Enter Password',
    id: 'confirm_password',
    type: 'password',
    name: 'confirm_password',
    defaultValue: '',
    errorMessage: 'Please input your password again!',
    placeholder: 'Re Enter your Password',
    required: true,
    // icon: 'LockOutlined',
    icon: <LockOutlined className="register-icon" />,
    rules: [
      {
        required: true,
        message: 'Please input your password again!',
      },
    ],
  },
];
